# **days 12**

In [20]:
import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()       #by default 5 rows ahe shown
import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import expon



import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel


import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp


In [21]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]

df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
model = ols('Resp~Factor1*Factor2',df).fit()
res=sm.stats.anova_lm(model)

In [22]:
model =ols('Resp~Factor1+Factor2',df).fit()

In [23]:
res=sm.stats.anova_lm(model)

In [24]:
print(res)

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN


In [25]:
model =ols('Resp~Factor1*Factor2',df).fit()

In [26]:
res=sm.stats.anova_lm(model)

In [27]:
print(res)

                  df       sum_sq     mean_sq         F    PR(>F)
Factor2          1.0   176.333333  176.333333  0.483367  0.506590
Factor1          1.0    28.125000   28.125000  0.077097  0.788312
Factor1:Factor2  1.0     0.125000    0.125000  0.000343  0.985685
Residual         8.0  2918.416667  364.802083       NaN       NaN


**1-sample z test/ 1 sample t test**

This test is used to compare the sample mean of one sample sample against a calim value and establish whether their difference is statistically significant or not

**2-sample t test**

This test is used to compare the difference of means of two independent samples against a claim value and establish whether their difference is statistically significant or not

**Paired t test**

This test is used when we have two paired samples. The average difference between the paired values is compared against a claim values and establish whether their difference is statistically significant or not
The key word here is before-after

**One way ANOVA**

Used when we have multiple samples. This test compares all the pair of the means. It checks whether the difference of each pair of mean can be ignored or not OR can be considered to be equal to 0 or not.
The Ho in this case is that all the pair of means are equal

**Multi way ANOVA**

Used when we have multiple factors influencing the response. IN addition to their individual effect, we would also like to study the interactions between various factors.

**1-proportion test**

This test is used to compare the proportion calculated from a sample against a claim value and establish whether their difference is statistically significant or not

In [28]:
mu=500*0.7

In [29]:
mu

350.0

In [30]:
sd=(500*0.7*0.3)**0.5

In [31]:
sd

10.246950765959598

In [32]:
#what is the propability that is occur 300
binom.cdf(370,500,0.7) - binom.cdf(330,500,0.7)

np.float64(0.9488558323799914)

In [33]:
binom.cdf(370,500,0.7) - binom.cdf(329,500,0.7)

np.float64(0.9547133734363867)

In [34]:
norm.cdf(370.5,mu,sd) - norm.cdf(329.5,mu,sd)

np.float64(0.9545639632657537)

H0 pr<=0.4  Ha pr>0.4

In a sample of 400 students, 150 students are from MH

In [35]:
180/400

0.45

In [36]:
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

In [37]:
statsmodels.stats.proportion,proportions_ztest(180,400,0.4,alternative='larger')

(<module 'statsmodels.stats.proportion' from '/usr/local/lib/python3.12/dist-packages/statsmodels/stats/proportion.py'>,
 (np.float64(2.0100756305184238), np.float64(0.022211592425003045)))

In [38]:
norm.cdf(2.0100756305184238)

np.float64(0.977788407574997)

In [39]:
1- norm.cdf(0.022211592425003045)

np.float64(0.4911395852273611)

**2-proportion test**

This test is used to compare the difference of two proportions calculated from two samples against a claim value and establish whether their difference is statistically significant or not

In [40]:
#pune CDAC claims that they have atleast 85 more engineer as compared to CDAC kharghar

In [ ]:
# H0 pr(pune) - pr(kharghar) >= 0.08
# Ha pr(pune -pr(kharghar)) < 0.08

In [ ]:
#In a sample of 70 student in pune , 40 were btech
#In a sample of 80 students in kharghar, 38 were btech

In [41]:
40/70 -38/80

0.09642857142857142

In [ ]:
#In a sample of 80 students in kharghar, 32 were btech

In [42]:
40/70 -32/80

0.17142857142857137

In [ ]:
#In a sample of 80 students in kharghar, 48 were btech

In [43]:
40/70 - 48/80

-0.02857142857142858

In [45]:
engg = np.array([40,48])

In [46]:
total = np.array([70,80])

In [47]:
statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

# **Chi square test for goodness of fit**

Used when there are multiple categories. The counts obtained for each category would be compared aginst the claimed pattern to check whether the counts follow the pattern or not. The standard Ho is that the counts follow the pattern

In [48]:
# claimed pattern for the qualifications
# Btech -0.4, Mtech -0.1, MCA -0.3, Msc -0.2
# Btech-50 , Mtech-20, MCA-45, MSC-25

# wheather counts obtained from sample follow the pattern or not

In [49]:
count=np.array([50,20,45,25])
pattern = np.array([0.4,0.1,0.3,0.2])


In [50]:
exp_counts = sum(count) * pattern

In [51]:
exp_counts

array([56., 14., 42., 28.])

In [52]:
from scipy.stats import chisquare

In [53]:
scipy.stats.chisquare(count,f_exp =exp_counts)

Power_divergenceResult(statistic=np.float64(3.7500000000000004), pvalue=np.float64(0.2897557811933843))

# **test stats increase p value decrease**


p values goes down null hypothesis rejected

In [42]:
counts=np.array([70,10,35,45])      # new count

In [43]:
exp_counts = sum(counts) * pattern

p-value<0.05, so we reject Ho

In [44]:
exp_counts

array([64., 16., 48., 32.])

In [4]:
from scipy.stats import chisquare

In [46]:
scipy.stats.chisquare(counts,f_exp =exp_counts)

Power_divergenceResult(statistic=np.float64(11.614583333333334), pvalue=np.float64(0.008827096989130126))

In [47]:
sum((exp_counts - counts)**2/exp_counts)

np.float64(11.614583333333334)

In [48]:
(exp_counts - counts)**2/exp_counts

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

# **Chi Square degree of Association**

Chi square test for degree pf association
Used when we wish to check and establish whether one categorical data has an effect on the other categorical data or not

**Ho: categorical variable A does not influence the choice from categorical variable B**

In [5]:
from scipy.stats import chi2_contingency

In [ ]:
#three foods - south.maharashtraian , gujarati

In [50]:
food=np.array([[45,70,60],[70,40,25]])

In [51]:
food

array([[45, 70, 60],
       [70, 40, 25]])

In [52]:
scipy.stats.chi2_contingency(food)      #null hypothesis would be rejected

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))

# dregre of freedom = (no.of rows - 1) * (no. of column - 1)

# **day 13**

In [6]:
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

In [ ]:
data = np.array([40,70,60],[70,40,25])

# **One sample possion rate**

This test is used when wish to compare the rate of which. event against the claim value and which establish wheather that differance is statistically significat or not

In [ ]:
# A good class would ask atleast 20 question every day
# H0 n>20
# Ha n<20   left tail test

In [54]:
questions=[14,19,24,18,17,23,21,18,19,17]

In [55]:
test_poisson(sum(questions),len(questions),20,method='score',alternative='smaller')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = np.float64(-0.7071067811865475)
pvalue = np.float64(0.23975006109347674)
distribution = 'normal'
method = 'score'
alternative = 'smaller'
rate = 19.0
nobs = 10
tuple = (np.float64(-0.7071067811865475), np.float64(0.23975006109347674))

# **Two sample possion rate**

Used when we have two samples and the difference of the average counts of an event has to be compared against a claim value and establish whether the difference is statistically significant or not.

In [56]:
from statsmodels.stats.rates import test_poisson_2indep

In [ ]:
# DBDA batch asks atleast 6 quesdtion/ pay more than AI batch
# H0 : avg-count(DBDA) - avg_count(AI) >=6
# Ha : avg_count(DBDA) - avg_count(AI) <6
# In DBDA's 12 days of training , 145 question were asked
# In AI's 5 days of training, 45 quetsion were asked

In [57]:
test_poisson_2indep(145,12,45,5,value=6,compare='diff',method='score',alternative='smaller')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = np.float64(-1.8159331852877063)
pvalue = np.float64(0.0346903109982295)
distribution = 'normal'
compare = 'diff'
method = 'score'
alternative = 'smaller'
rates = (np.float64(12.083333333333334), np.float64(9.0))
ratio = np.float64(1.3425925925925926)
diff = np.float64(3.083333333333334)
value = 6
rates_cmle = (np.float64(13.34021539496958), np.float64(7.3402153949695785))
ratio_null = None
tuple = (np.float64(-1.8159331852877063), np.float64(0.0346903109982295))

# **One Variance Test**

Used when the variance of a sample has to be compared against a claim value and establish whether their difference from 1 is statistically significant or not

**practical signoficant** >>>> changes from person to person




In [58]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='faithful')

In [59]:
erupt=df.eruptions

In [60]:
np.var(erupt,ddof=1)      # variance

1.3027283328494672

In [ ]:
# H0 variance (erupt) < 1.1
# H0 variance (erupt) <= 1.1
# H0 variance (erupt) > 1.1   right tail test
# TS =(n-1)* variance / (claim value)

In [61]:
ts = (len(erupt)-1)*np.var(erupt,ddof=1)/1.1          #test statistics

In [62]:
ts

320.94488927473236

In [63]:
from scipy.stats import chi2

In [64]:
p_value = 1 - chi2.cdf(ts,len(erupt)-1).      # this formula is used for convert test statistics to p values

In [65]:
p_value

np.float64(0.019972202957899476)

In [70]:
p_value =chi2.sf(ts,len(erupt)-1)

In [71]:
p_value

np.float64(0.019972202957899473)

In [72]:
np.var(erupt,ddof=1)/1.1

1.1842984844086064

In [73]:
# H0 variance (erupt) <= 1.1

# **Two Variance Test**

Used when we have two samples. The ratio of the variances has to be compared against a claim value and establish whether their difference from 1 is statistically significant or not

In [74]:
samp1 = erupt[30:70]
samp2 = erupt[130:180]

In [75]:
np.var(samp1,ddof=1)/np.var(samp2,ddof=1)

1.2115512965696353

In [ ]:
# H0 : var (samp1)/var(samp2) >= 1.4
# Ha : var (samp1)/var(samp2) < 1.4

In [ ]:
# f test used whenever we take ratio of variances

In [80]:
samp_ratio = np.var(samp1,ddof=1)/np.var(samp2,ddof=1)

In [84]:
ts=samp_ratio/1.4

In [85]:
from scipy.stats import f

In [86]:
f.cdf(ts,len(samp1)-1,len(samp2)-1)

np.float64(0.32252763139863083)