In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import os

In [ ]:
os.getcwd()     #get current working directory

'/content'

In [ ]:
os.chdir("/content/drive/MyDrive")

In [ ]:
os.getcwd

<function posix.getcwd()>

In [ ]:
import pandas as pd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')

In [ ]:
df.head()       #by default 5 rows ahe shown

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [ ]:
df.head(3)

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27


In [ ]:
df.tail(4)

,MaterialID,Location,Quantity
46,AXCP-78,MWH-2,85
47,AXCP-78,MWH-3,29
48,AXCP-78,MWH-1,75
49,DDBN-89,MWH-1,39


In [ ]:
df.shape      #reports the no. of rows and columns in df

(50, 3)

In [ ]:
np.unique(df['MaterialID']) #reports the unique material id

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
np.unique(df.MaterialID)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
len(np.unique(df.MaterialID))   #no. of unique material id

6

In [ ]:
len(np.unique(df.Location))   #no. of unique Location

5

In [ ]:
np.unique(df.Location)

array(['MWH-1', 'MWH-2', 'MWH-3', 'MWH-4', 'MWH-5'], dtype=object)

In [ ]:

df.columns.values # gives name of the columns

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [ ]:
df.columns.values[0]

'MaterialID'

In [ ]:
df.columns.values[0]='MatID'   #Modify column name

In [ ]:
df.head()

,MatID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [ ]:
ind=np.where(df.Quantity>=70)

In [ ]:
ind

(array([ 5,  9, 12, 15, 17, 21, 23, 24, 25, 27, 33, 38, 39, 46, 48]),)

In [ ]:
len(ind[0])

15

In [ ]:
(df.Quantity>=70).sum()

np.int64(15)

In [ ]:
df1=df.iloc[ind]

In [ ]:
df1

,MatID,Location,Quantity
5,TMI-43T,MWH-4,78
9,TMI-43T,MWH-1,120
12,TMI-43T,MWH-4,76
15,GCVB-79,MWH-2,87
17,SDRT-67,MWH-5,102
21,TMI-43T,MWH-4,75
23,DDBN-89,MWH-5,71
24,AXCP-78,MWH-1,152
25,AXCP-78,MWH-1,109
27,LXCV-21,MWH-5,83


In [ ]:
df.loc[ind]

,MatID,Location,Quantity
5,TMI-43T,MWH-4,78
9,TMI-43T,MWH-1,120
12,TMI-43T,MWH-4,76
15,GCVB-79,MWH-2,87
17,SDRT-67,MWH-5,102
21,TMI-43T,MWH-4,75
23,DDBN-89,MWH-5,71
24,AXCP-78,MWH-1,152
25,AXCP-78,MWH-1,109
27,LXCV-21,MWH-5,83


In [ ]:
ind=np.where((df.Quantity>=70) & (df.Location=='MWH-1'))

In [ ]:
len(ind[0])

5

In [ ]:
df1=df.iloc[ind]

In [ ]:
df1

,MatID,Location,Quantity
9,TMI-43T,MWH-1,120
24,AXCP-78,MWH-1,152
25,AXCP-78,MWH-1,109
39,AXCP-78,MWH-1,145
48,AXCP-78,MWH-1,75


In [ ]:
ind=np.where((df.Quantity>=70) | (df.Location=='MWH-1'))

In [ ]:
len(ind[0])

21

In [ ]:
#what is the total weight of all consignment stored in mwh-2
temp=df.iloc[np.where(df.Location=='MWH-2')]

In [ ]:
sum(temp.Quantity)

397

In [ ]:
sum(df.iloc[np.where(df.Location=='MWH-2')].Quantity)

397

In [ ]:
#Quantity value is less than 30
(df.Quantity<50).sum()

np.int64(24)

In [ ]:
ind=np.where(df.Quantity<50)

In [ ]:
df=df.drop(ind[0])

In [ ]:
df1.shape

(5, 3)

In [ ]:
ind=np.where(df.Quantity>=70)

In [ ]:
df1=df.iloc[ind[0]]

In [ ]:
df1.head()

,MatID,Location,Quantity
5,TMI-43T,MWH-4,78
9,TMI-43T,MWH-1,120
12,TMI-43T,MWH-4,76
15,GCVB-79,MWH-2,87
17,SDRT-67,MWH-5,102


In [ ]:
df1.head(7)

,MatID,Location,Quantity
5,TMI-43T,MWH-4,78
9,TMI-43T,MWH-1,120
12,TMI-43T,MWH-4,76
15,GCVB-79,MWH-2,87
17,SDRT-67,MWH-5,102
21,TMI-43T,MWH-4,75
23,DDBN-89,MWH-5,71


In [ ]:
df1.iloc[5]

,21
MatID,TMI-43T
Location,MWH-4
Quantity,75


In [ ]:
df1.loc[5]

,5
MatID,TMI-43T
Location,MWH-4
Quantity,78


In [ ]:
df1=df.iloc[ind[0]].reset_index(drop=True)

In [ ]:
df1

,MatID,Location,Quantity
0,TMI-43T,MWH-4,78
1,TMI-43T,MWH-1,120
2,TMI-43T,MWH-4,76
3,GCVB-79,MWH-2,87
4,SDRT-67,MWH-5,102
5,TMI-43T,MWH-4,75
6,DDBN-89,MWH-5,71
7,AXCP-78,MWH-1,152
8,AXCP-78,MWH-1,109
9,LXCV-21,MWH-5,83


In [ ]:
min(df.Quantity)

10

In [ ]:
max(df.Quantity)

152

In [ ]:
df.shape

(50, 3)

In [ ]:
grd=[]
for ctr in df.Quantity:
  if ctr>0 and ctr<=50:
    grd.append('A')
  elif ctr>50 and ctr<100:
    grd.append('B')
  else:
    grd.append('C')
df['Grade']=grd

In [ ]:
df.head()

,MaterialID,Location,Quantity,Grade
0,TMI-43T,MWH-4,34,A
1,AXCP-78,MWH-1,67,B
2,LXCV-21,MWH-2,27,A
3,AXCP-78,MWH-5,65,B
4,AXCP-78,MWH-4,36,A


In [ ]:
df.Grade.value_counts()

,count
Grade,
A,24
B,20
C,6


In [ ]:
#write a program output of  warehouse mwh -2 total quantity high

In [ ]:
df=pd.read_excel('CDAC_DataBook (1).xlsx', sheet_name='EmpInfo')

In [ ]:
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,NaN,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [ ]:
ind=np.where(df.Deptt.isnull())

In [ ]:
ind

(array([3, 5]),)

In [ ]:
df1=df.drop(ind[0])     #df1 has all row where deptt is not missing

In [ ]:
df1

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
4,Rishi,R475,Prodn,DF453278
6,Deepak,NaN,Quality,RF453432


In [ ]:
df2=df.iloc[ind[0]]       #df2 has all rows with missing values for deptt

In [ ]:
df2

,Name,EmpID,Deptt,Passport
3,Arjun,A342,NaN,RF453432
5,Chetan,NaN,NaN,ER534867


In [ ]:
df2=df.iloc[ind[0]].reset_index(drop=True)

In [ ]:
df2

,Name,EmpID,Deptt,Passport
0,Arjun,A342,NaN,RF453432
1,Chetan,NaN,NaN,ER534867


In [ ]:
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,NaN,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [ ]:
ind =np.where((df.EmpID.isnull()) & (df.Deptt.isnull()))

In [ ]:
ind

(array([5]),)

In [ ]:
ind =np.where(df.Deptt.isnull())  #stores the row index where the values under the deppt column is missing

In [ ]:
ind

(array([3, 5]),)

In [ ]:

#when missing values in tables
#remove that row
#replace missing values with some other values
#for numeric column --median
#for string --mode


In [ ]:
df.loc[ind[0],'Deptt']='Fresher'

In [ ]:
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,Fresher,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,Fresher,ER534867
6,Deepak,NaN,Quality,RF453432


In [ ]:
df.iloc[ind[0],2]='Fresher'

In [ ]:
#how many values arae mising in empid
df.EmpID.isnull()

,EmpID
0,False
1,False
2,False
3,False
4,False
5,True
6,True


In [ ]:
df.EmpID.isnull().sum()       #count the missing values

np.int64(2)

In [ ]:
temp=df.dropna()          #drops all rows where there is missing values in any column

In [ ]:
temp

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
3,Arjun,A342,Fresher,RF453432
4,Rishi,R475,Prodn,DF453278


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      6 non-null      object
 1   EmpID     5 non-null      object
 2   Deptt     7 non-null      object
 3   Passport  7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes


In [ ]:
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,Fresher,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,Fresher,ER534867
6,Deepak,NaN,Quality,RF453432


cleaning

handling missisng values

handling duplicate values

In [ ]:
ind =np.where(df.Passport.duplicated())      #it gives second occurrecnce not first

In [ ]:
ind

(array([2, 4, 6]),)

In [ ]:
ind =np.where(df.Passport.duplicated(keep=False))      #it also gives first occurrecnce

In [ ]:
ind

(array([0, 2, 3, 4, 6]),)

In [ ]:
ind =np.where(df.Passport.duplicated(keep=first))

AttributeError: 'DataFrame' object has no attribute 'Passport'

In [ ]:
ind =np.where(df.Passport.duplicated(keep='first'))

In [ ]:
ind

(array([2, 4, 6]),)

In [ ]:
ind =np.where(df.Passport.duplicated(keep='last'))

In [ ]:
ind

(array([0, 2, 3]),)

**data** **validation**

In [ ]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')

In [ ]:
df1=df.iloc[ind[0]]

In [ ]:
df1

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65


**group by command**

In [ ]:
grp1=df.groupby("Location")   #does grouping on the column location

In [ ]:
grp1

In [ ]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [ ]:
grp1.get_group('MWH-2')

,MaterialID,Location,Quantity
2,LXCV-21,MWH-2,27
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
15,GCVB-79,MWH-2,87
35,GCVB-79,MWH-2,31
36,GCVB-79,MWH-2,28
42,SDRT-67,MWH-2,31
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85


In [ ]:
df1=grp1.get_group('MWH-2').reset_index(drop=True)

In [ ]:
df1

,MaterialID,Location,Quantity
0,LXCV-21,MWH-2,27
1,TMI-43T,MWH-2,29
2,GCVB-79,MWH-2,10
3,GCVB-79,MWH-2,87
4,GCVB-79,MWH-2,31
5,GCVB-79,MWH-2,28
6,SDRT-67,MWH-2,31
7,DDBN-89,MWH-2,69
8,AXCP-78,MWH-2,85


In [ ]:
pd.concat([grp1.get_group('MWH-2'),grp1.get_group('MWH-3')])

,MaterialID,Location,Quantity
2,LXCV-21,MWH-2,27
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
15,GCVB-79,MWH-2,87
35,GCVB-79,MWH-2,31
36,GCVB-79,MWH-2,28
42,SDRT-67,MWH-2,31
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85
14,TMI-43T,MWH-3,65


In [ ]:
df2=grp1.Quantity.agg(np.sum)
df2    #location is the title of labels

/tmp/ipykernel_1520/1700898873.py:1: FutureWarning: The provided callable <function sum at 0x780997530860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2=grp1.Quantity.agg(np.sum)


,Quantity
Location,
MWH-1,889
MWH-2,397
MWH-3,174
MWH-4,728
MWH-5,697


In [ ]:
type(df2)

pandas.core.series.Series

In [ ]:
df2.index

Index(['MWH-1', 'MWH-2', 'MWH-3', 'MWH-4', 'MWH-5'], dtype='object', name='Location')

In [ ]:
df2=grp1.Quantity.agg(np.sum).reset_index()
df2

/tmp/ipykernel_1520/1707064811.py:1: FutureWarning: The provided callable <function sum at 0x780997530860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2=grp1.Quantity.agg(np.sum).reset_index()


,Location,Quantity
0,MWH-1,889
1,MWH-2,397
2,MWH-3,174
3,MWH-4,728
4,MWH-5,697


In [ ]:
grp1.Quantity.agg(np.mean)          #889/11=80.818182     quantity/size=mean

/tmp/ipykernel_1520/719844975.py:1: FutureWarning: The provided callable <function mean at 0x780997531940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg(np.mean)


,Quantity
Location,
MWH-1,80.818182
MWH-2,44.111111
MWH-3,43.500000
MWH-4,48.533333
MWH-5,63.363636


In [ ]:
grp1.Quantity.agg(np.size)

,Quantity
Location,
MWH-1,11
MWH-2,9
MWH-3,4
MWH-4,15
MWH-5,11


In [ ]:
grp1.Quantity.agg(['sum','mean','size'])

,sum,mean,size
Location,,,
MWH-1,889,80.818182,11
MWH-2,397,44.111111,9
MWH-3,174,43.500000,4
MWH-4,728,48.533333,15
MWH-5,697,63.363636,11


In [ ]:
locn1=['Mumbai','Mumbai','Mumbai','pune','pune']

In [ ]:
course=['AI','ML','DS','AI','DS']

In [ ]:
marks1=[45,78,65,35,89]

In [ ]:
marks2=[80,76,59,82,49]

In [ ]:
mydf=pd.DataFrame({'Nandini' : marks1,'nandu':marks2},index=[locn1,course])

In [ ]:
mydf

Nandini  nandu
Mumbai AI       45     80
       ML       78     76
       DS       65     59
pune   AI       35     82
       DS       89     49

In [ ]:
mydf.index.names=['Location','subject']

In [ ]:
mydf

Nandini  nandu
Location subject                
Mumbai   AI            45     80
         ML            78     76
         DS            65     59
pune     AI            35     82
         DS            89     49

In [ ]:
mydf.loc['Mumbai']

,Nandini,nandu
subject,,
AI,45,80
ML,78,76
DS,65,59


In [ ]:
mydf.loc['Mumbai','AI']

,Mumbai
,AI
Nandini,45
nandu,80


In [ ]:
mydf

Nandini  nandu
Location subject                
Mumbai   AI            45     80
         ML            78     76
         DS            65     59
pune     AI            35     82
         DS            89     49

In [ ]:
mydf.xs('AI',level='subject')

,Nandini,nandu
Location,,
Mumbai,45,80
pune,35,82


## **Day 4**

In [ ]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')

In [ ]:
grp1=df.groupby('MaterialID')

In [ ]:
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
grp1.get_group('SDRT-67')

,MaterialID,Location,Quantity
10,SDRT-67,MWH-1,34
11,SDRT-67,MWH-4,58
16,SDRT-67,MWH-5,12
17,SDRT-67,MWH-5,102
41,SDRT-67,MWH-1,57
42,SDRT-67,MWH-2,31


In [ ]:
grp1.Quantity.agg(np.sum)

/tmp/ipykernel_610/1212771957.py:1: FutureWarning: The provided callable <function sum at 0x7dfef5120860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg(np.sum)


,Quantity
MaterialID,
AXCP-78,898
DDBN-89,383
GCVB-79,182
LXCV-21,243
SDRT-67,294
TMI-43T,885


In [ ]:
grp1.Quantity.agg('sum')      #grouping is always done in categorical data

,Quantity
MaterialID,
AXCP-78,898
DDBN-89,383
GCVB-79,182
LXCV-21,243
SDRT-67,294
TMI-43T,885


In [ ]:
grp1=df.groupby(['Location','MaterialID'])

In [ ]:
grp1.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [ ]:
grp1.Quantity.agg('sum')

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [ ]:
newdf=grp1.agg([np.sum,np.mean,np.size])
newdf

/tmp/ipykernel_610/2365417064.py:1: FutureWarning: The provided callable <function sum at 0x7dfef5120860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  newdf=grp1.agg([np.sum,np.mean,np.size])
/tmp/ipykernel_610/2365417064.py:1: FutureWarning: The provided callable <function mean at 0x7dfef5121940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  newdf=grp1.agg([np.sum,np.mean,np.size])


Quantity                 
                         sum        mean size
Location MaterialID                          
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1
MWH-4    AXCP-78          36   36.000000    1
         DDBN-89          75   37.500000    2
         SDRT-67          58   58.000000    1
         TMI-43T         559   50.818182   11
MWH-5    AXCP-78         200   66.666667    3
         DDBN-89          71   71.000000    1
         GCVB-79          26   26.000000    1
         LXCV-21         174   58.000000    3
         SDRT-67         114   57.000000    2
         TMI-43T         112  112.000000    1

In [ ]:
newdf.loc[['MWH-1','MWH-2']]

Quantity                 
                         sum        mean size
Location MaterialID                          
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1

# **sorting of data frame**

In [ ]:
df.head()

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [ ]:
df_sorted=df.sort_values('Quantity')

In [ ]:
df_sorted.head()

,MaterialID,Location,Quantity
8,GCVB-79,MWH-2,10
16,SDRT-67,MWH-5,12
34,GCVB-79,MWH-5,26
30,DDBN-89,MWH-4,27
2,LXCV-21,MWH-2,27


In [ ]:
df_sorted.tail()

,MaterialID,Location,Quantity
25,AXCP-78,MWH-1,109
33,TMI-43T,MWH-5,112
9,TMI-43T,MWH-1,120
39,AXCP-78,MWH-1,145
24,AXCP-78,MWH-1,152


In [ ]:
df_sorted=df.sort_values('Quantity',ascending=False)

In [ ]:
df_sorted.head()

,MaterialID,Location,Quantity
24,AXCP-78,MWH-1,152
39,AXCP-78,MWH-1,145
9,TMI-43T,MWH-1,120
33,TMI-43T,MWH-5,112
25,AXCP-78,MWH-1,109


In [ ]:
df_sorted=df.sort_values(['MaterialID','Location','Quantity'])

In [ ]:
df_sorted

,MaterialID,Location,Quantity
1,AXCP-78,MWH-1,67
48,AXCP-78,MWH-1,75
25,AXCP-78,MWH-1,109
39,AXCP-78,MWH-1,145
24,AXCP-78,MWH-1,152
46,AXCP-78,MWH-2,85
47,AXCP-78,MWH-3,29
4,AXCP-78,MWH-4,36
3,AXCP-78,MWH-5,65
37,AXCP-78,MWH-5,65


In [ ]:
df_sorted=df.sort_values(['MaterialID','Location','Quantity'],ascending=[True,False,True])

In [ ]:
df_sorted

,MaterialID,Location,Quantity
3,AXCP-78,MWH-5,65
37,AXCP-78,MWH-5,65
38,AXCP-78,MWH-5,70
4,AXCP-78,MWH-4,36
47,AXCP-78,MWH-3,29
46,AXCP-78,MWH-2,85
1,AXCP-78,MWH-1,67
48,AXCP-78,MWH-1,75
25,AXCP-78,MWH-1,109
39,AXCP-78,MWH-1,145


## **merging the data frame**

In [ ]:
pune=pd.read_excel("CDAC_DataBook (1).xlsx",sheet_name='Pune')

In [ ]:
mumbai=pd.read_excel("CDAC_DataBook (1).xlsx",sheet_name='Mumbai')

In [ ]:
pune

,Name,Subject,Grade
0,Rakesh,Python,A
1,Manoj,MLPython,C
2,Vaibhav,Statistics,B
3,Hitesh,CommSkills,A
4,Suyash,ProjectMgmt,B
5,Vinod,AI,B


In [ ]:
mumbai

,Name,Subject,Grade
0,Vaibhav,Six Sigma,A
1,Deepika,Statistics,B
2,Arjun,CommSkills,A
3,Chetan,Python,A
4,Abhishek,MLPython,B
5,Vinod,AI,C


In [ ]:
pd.merge(pune,mumbai)

,Name,Subject,Grade


In [ ]:
pd.merge(pune,mumbai,on='Subject')      #by default commman ....intersection

,Name_x,Subject,Grade_x,Name_y,Grade_y
0,Rakesh,Python,A,Chetan,A
1,Manoj,MLPython,C,Abhishek,B
2,Vaibhav,Statistics,B,Deepika,B
3,Hitesh,CommSkills,A,Arjun,A
4,Vinod,AI,B,Vinod,C


In [ ]:
pune

,Name,Subject,Grade
0,Rakesh,Python,A
1,Manoj,MLPython,C
2,Vaibhav,Statistics,B
3,Hitesh,CommSkills,A
4,Suyash,ProjectMgmt,B
5,Vinod,AI,B


In [ ]:
mumbai

,Name,Subject,Grade
0,Vaibhav,Six Sigma,A
1,Deepika,Statistics,B
2,Arjun,CommSkills,A
3,Chetan,Python,A
4,Abhishek,MLPython,B
5,Vinod,AI,C


In [ ]:
#x---comimg from pune
#y== coming from  mumbai

In [ ]:
pd.merge(pune,mumbai,on='Subject',how='inner')

,Name_x,Subject,Grade_x,Name_y,Grade_y
0,Rakesh,Python,A,Chetan,A
1,Manoj,MLPython,C,Abhishek,B
2,Vaibhav,Statistics,B,Deepika,B
3,Hitesh,CommSkills,A,Arjun,A
4,Vinod,AI,B,Vinod,C


In [ ]:
pd.merge(pune,mumbai,on=['Subject','Grade'],how='inner')

,Name_x,Subject,Grade,Name_y
0,Rakesh,Python,A,Chetan
1,Vaibhav,Statistics,B,Deepika
2,Hitesh,CommSkills,A,Arjun


In [ ]:
pd.merge(pune,mumbai,on='Subject',how='outer')

,Name_x,Subject,Grade_x,Name_y,Grade_y
0,Vinod,AI,B,Vinod,C
1,Hitesh,CommSkills,A,Arjun,A
2,Manoj,MLPython,C,Abhishek,B
3,Suyash,ProjectMgmt,B,NaN,NaN
4,Rakesh,Python,A,Chetan,A
5,NaN,Six Sigma,NaN,Vaibhav,A
6,Vaibhav,Statistics,B,Deepika,B


In [ ]:
pune

,Name,Subject,Grade
0,Rakesh,Python,A
1,Manoj,MLPython,C
2,Vaibhav,Statistics,B
3,Hitesh,CommSkills,A
4,Suyash,ProjectMgmt,B
5,Vinod,AI,B


In [ ]:
mumbai

,Name,Subject,Grade
0,Vaibhav,Six Sigma,A
1,Deepika,Statistics,B
2,Arjun,CommSkills,A
3,Chetan,Python,A
4,Abhishek,MLPython,B
5,Vinod,AI,C


In [ ]:
pd.merge(pune,mumbai,on='Subject',how='left')

,Name_x,Subject,Grade_x,Name_y,Grade_y
0,Rakesh,Python,A,Chetan,A
1,Manoj,MLPython,C,Abhishek,B
2,Vaibhav,Statistics,B,Deepika,B
3,Hitesh,CommSkills,A,Arjun,A
4,Suyash,ProjectMgmt,B,NaN,NaN
5,Vinod,AI,B,Vinod,C
