In [1]:
import numpy as np


In [2]:
x1=[4,8,7,6,9]

In [3]:
str(x1)

'[4, 8, 7, 6, 9]'

In [4]:
type(x1)

list

In [7]:
a1=np.array(x1)

In [8]:
type(a1)

numpy.ndarray

In [9]:
a1=array(x1)

NameError: name 'array' is not defined

In [10]:
x2=[6,9,1,3,2]

In [11]:
a2=np.array([x1,x2])

In [12]:
a2

array([[4, 8, 7, 6, 9],
       [6, 9, 1, 3, 2]])

In [13]:
x1=list(range(11))

In [14]:
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
x1=list(range(11))

In [16]:
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
a1=np.arange(11)

In [18]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a1=np.arange(3,14)

In [20]:
a1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [21]:
a1=np.arange(5,24,3)

In [22]:
a1

array([ 5,  8, 11, 14, 17, 20, 23])

In [23]:
a1=np.arange(5,24,4)

In [24]:
a1

array([ 5,  9, 13, 17, 21])

In [25]:
a1=np.arange(24,5,-2)

In [26]:
a1

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6])

In [27]:
a1=np.arange(24,5,-1)

In [28]:
a1

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6])

In [30]:
a1=np.arange(25,7,-5)

In [31]:
a1

array([25, 20, 15, 10])

In [32]:
x1=np.linspace(10,20,3)

In [33]:
x1

array([10., 15., 20.])

In [34]:
x1=np.linspace(10,20,7)

In [35]:
x1

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ])

In [36]:
x1=np.linspace(10,30,7,endpoint=False)

In [37]:
x1

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714])

In [38]:
a1=np.array([4,8,6,5,9])

In [39]:
a1

array([4, 8, 6, 5, 9])

In [41]:
np.append(a1,3)

array([4, 8, 6, 5, 9, 3])

In [42]:
a1

array([4, 8, 6, 5, 9])

In [43]:
a1=np.append(a1,3)

In [44]:
a1

array([4, 8, 6, 5, 9, 3])

In [46]:
a2=np.array([2,9,8])

In [47]:
a2

array([2, 9, 8])

In [48]:
a3=np.concatenate((a1,a2))

In [49]:
a3

array([4, 8, 6, 5, 9, 3, 2, 9, 8])

In [52]:
x2=[5,4,3,6,7]

In [53]:
del x2[1]

In [54]:
x2

[5, 3, 6, 7]

In [55]:
z=x2.pop(2)

In [56]:
x2

[5, 3, 7]

In [57]:
z

6

In [58]:
a1=np.array([3,6,5,7,8])

In [59]:
a2=np.insert(a1,3,9)

In [60]:
a2

array([3, 6, 5, 9, 7, 8])

In [61]:
np.delete(a2,2)

array([3, 6, 9, 7, 8])

In [62]:
a2

array([3, 6, 5, 9, 7, 8])

In [63]:
a2=np.delete(a2,2)

In [64]:
a2

array([3, 6, 9, 7, 8])

In [68]:
a1=np.array([3,2,6,7,8,5,4,6])

In [69]:
len(a1)

8

In [70]:
a2=a1.reshape(4,2)

In [71]:
a2

array([[3, 2],
       [6, 7],
       [8, 5],
       [4, 6]])

In [73]:
a3=a1.reshape(-1,1)

In [75]:
a3

array([[3],
       [2],
       [6],
       [7],
       [8],
       [5],
       [4],
       [6]])

In [77]:
a4=a1.reshape(-1,2)

In [78]:
a4

array([[3, 2],
       [6, 7],
       [8, 5],
       [4, 6]])

In [79]:
a4[2]

array([8, 5])

In [80]:
a4[2,:]

array([8, 5])

In [81]:
a4[:,1]

array([2, 7, 5, 6])

In [82]:
a4[[2,3],:]

array([[8, 5],
       [4, 6]])

In [83]:
a4[:,[0,1]]

array([[3, 2],
       [6, 7],
       [8, 5],
       [4, 6]])

In [84]:
newcol=np.array([3,1,7,9])

In [85]:
newcol=newcol.reshape(-1,1)

In [86]:
newcol

array([[3],
       [1],
       [7],
       [9]])

In [88]:
a4=np.hstack([a4,newcol])

In [89]:
a4

array([[3, 2, 3],
       [6, 7, 1],
       [8, 5, 7],
       [4, 6, 9]])

In [90]:
newrow=np.array([1,2,3])

In [91]:
a4=np.vstack([a4,newrow])

In [92]:
a4

array([[3, 2, 3],
       [6, 7, 1],
       [8, 5, 7],
       [4, 6, 9],
       [1, 2, 3]])

In [93]:
a4=np.insert(a4,3,[10,14,17],axis=0)

In [94]:
a4

array([[ 3,  2,  3],
       [ 6,  7,  1],
       [ 8,  5,  7],
       [10, 14, 17],
       [ 4,  6,  9],
       [ 1,  2,  3]])

In [95]:
a4=np.insert(a4,2,[2,3,4,5,6,8],axis=1)

In [96]:
a4

array([[ 3,  2,  2,  3],
       [ 6,  7,  3,  1],
       [ 8,  5,  4,  7],
       [10, 14,  5, 17],
       [ 4,  6,  6,  9],
       [ 1,  2,  8,  3]])

In [97]:
a5=np.delete(a4,(1,3),axis=0)

In [98]:
a5

array([[3, 2, 2, 3],
       [8, 5, 4, 7],
       [4, 6, 6, 9],
       [1, 2, 8, 3]])

broadcasting

In [99]:
a1=np.array([4,7,6,8,9])

In [100]:
a2=np.array([4,2,7,6,3])

In [101]:
a1+5

array([ 9, 12, 11, 13, 14])

In [102]:
a3=a1+5

In [103]:
a3

array([ 9, 12, 11, 13, 14])

In [104]:
a3=2*a1 + 5

In [105]:
a3

array([13, 19, 17, 21, 23])

In [106]:
a1

array([4, 7, 6, 8, 9])

In [107]:
a2

array([4, 2, 7, 6, 3])

In [108]:
a1+a2

array([ 8,  9, 13, 14, 12])

In [109]:
a1=np.array([3,5,4,6,7,9,3,1,2,6,7,9])

In [110]:
len(a1)

12

In [111]:
a2=a1.reshape(3,4)

In [112]:
a2

array([[3, 5, 4, 6],
       [7, 9, 3, 1],
       [2, 6, 7, 9]])

In [113]:
a3=np.array([2,4,6,8])

In [114]:
a2+a3

array([[ 5,  9, 10, 14],
       [ 9, 13,  9,  9],
       [ 4, 10, 13, 17]])

In [115]:
a2

array([[3, 5, 4, 6],
       [7, 9, 3, 1],
       [2, 6, 7, 9]])

In [116]:
a3=np.array([3,4,5])

In [118]:
a3=a3.reshape(-1,1)

In [119]:
a3

array([[3],
       [4],
       [5]])

In [120]:
a2+a3

array([[ 6,  8,  7,  9],
       [11, 13,  7,  5],
       [ 7, 11, 12, 14]])

In [121]:
a1

array([3, 5, 4, 6, 7, 9, 3, 1, 2, 6, 7, 9])

In [122]:
a1[[1,3,4]]

array([5, 6, 7])

In [123]:
a1[1]

np.int64(5)

ind=np.where(<condition>)

q1.where are the values which are greater than 4

ind[0]

q2.how many values are greater than 4

len(ind[0])

(a1>4).sum()


q3.what are the values which are greater than 4

a1[ind[0]]

In [124]:
ind=np.where(a1>4)

In [125]:
ind

(array([ 1,  3,  4,  5,  9, 10, 11]),)

In [ ]:
#input to np.where command is the condition that needs to be check

#output of the np.where command are the indices where that condition that found to be true

In [126]:
ind=np.where(a1>=4)

In [127]:
ind

(array([ 1,  2,  3,  4,  5,  9, 10, 11]),)

In [128]:
type(ind)

tuple

In [129]:
len(ind)

1

In [130]:
len(ind[0])

8

In [142]:
a1=np.array([5,8,2,1,6,9,3,6])

In [143]:
ind=np.where(a1>4)

In [144]:
ind

(array([0, 1, 4, 5, 7]),)

In [145]:
len(ind)

1

In [146]:
len(ind[0])

5

In [147]:
ind[0]

array([0, 1, 4, 5, 7])

In [148]:
(a1>4).sum()

np.int64(5)

In [149]:
a1[ind]

array([5, 8, 6, 9, 6])

In [150]:
a1[ind[0]]    #go with this option rather than above one

array([5, 8, 6, 9, 6])

In [131]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns


In [151]:
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [132]:
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols


In [152]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [133]:
x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally


In [153]:
x3

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [134]:
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically



In [154]:
x4

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]),
 array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31],
        [37, 38, 39],
        [45, 46, 47]])]

In [166]:
b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])


In [167]:
c = sorted(b)          #sorts the array in increasing order


In [168]:
c = sorted(b)[::-1]    # sorts the array in the decreasing order

In [169]:
c

[np.int64(9),
 np.int64(8),
 np.int64(7),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1)]

In [181]:
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged


array([1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [182]:
b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns


In [183]:
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [184]:
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged


array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [185]:
np.sort(b,axis=0)   # column wise values will be changed. Row values are only rearranged

array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [186]:
np.sort(b,axis=1)

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [187]:
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [188]:
ind=np.where(b>=4)

In [189]:
ind

(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))

In [191]:
# repeat block 3 times
r1=[5,8,3]

In [192]:
r2=r1*3

In [193]:
r2

[5, 8, 3, 5, 8, 3, 5, 8, 3]

In [194]:
a1=np.array([2,6,5,4])

In [197]:
a2=np.repeat(a1,3)

In [198]:
a2

array([2, 2, 2, 6, 6, 6, 5, 5, 5, 4, 4, 4])

In [199]:
#individually repeat
a2=np.repeat(a1,[2,4,3,2])

In [200]:
a2

array([2, 2, 6, 6, 6, 6, 5, 5, 5, 4, 4])

In [201]:
a1=np.array([4,7,6,1,3,8,7,2])

In [202]:
np.sort(a1)

array([1, 2, 3, 4, 6, 7, 7, 8])

In [207]:
np.argsort(a1)

array([3, 7, 4, 0, 2, 1, 6, 5])

In [ ]:
#output of the argsort command gives indexes lowest to highest
#list of the indices will be the output of the argsort cmd of the sorted array

In [208]:
a1[np.argsort(a1)]

array([1, 2, 3, 4, 6, 7, 7, 8])

In [209]:
a1=np.array([6,5,4,8,7,6,2,2,5,7,1,8,1])

In [210]:
len(a1)

13

In [211]:
np.unique(a1)

array([1, 2, 4, 5, 6, 7, 8])

In [212]:
np.unique(a1,return_counts=True)

(array([1, 2, 4, 5, 6, 7, 8]), array([2, 2, 1, 2, 2, 2, 2]))

In [214]:
np.unique(a1,return_index=True) #first occurance of value it will give index of that

(array([1, 2, 4, 5, 6, 7, 8]), array([10,  6,  2,  1,  0,  4,  3]))

In [216]:
np.where(a1==1)

(array([10, 12]),)

In [217]:
np.where(a1==2)

(array([6, 7]),)