In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a1=np.array([3,7,6,1,8,9])

In [ ]:
a2=np.array([2,4,5,8,10,3,6])

In [ ]:
#intersection
np.intersect1d(a1,a2)

array([3, 6, 8])

In [ ]:
#union
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#differance
np.setdiff1d(a1,a2)

array([1, 7, 9])

In [ ]:
a1

array([3, 7, 6, 1, 8, 9])

In [ ]:
a2

array([ 2,  4,  5,  8, 10,  3,  6])

In [ ]:
np.setdiff1d(a2,a1)

array([ 2,  4,  5, 10])

In [ ]:
#xor gate
np.setxor1d(a1,a2)

array([ 1,  2,  4,  5,  7,  9, 10])

In [ ]:
#logical array
np.isin(a1,a2)

array([ True, False,  True, False,  True, False])

In [ ]:

x1=np.array([2,3,-4])
x2=np.array([3,-2,1])

In [ ]:
np.dot(x1,x2)           #vector dot product of two vector

np.int64(-4)

In [ ]:
#linear algebra
from numpy import linalg

In [ ]:
x3=np.array([[1,2,3],[0,1,2],[1,1,0]])

In [ ]:
np.linalg.det(x3)    #determinant

np.float64(-1.0)

In [ ]:
np.cross(x1,x2)       # cross product of two vector

array([ -5, -14, -13])

In [ ]:

from numpy import random

In [ ]:
np.random.rand(10)

array([0.10265274, 0.58657687, 0.78959792, 0.93603517, 0.80915785,
       0.83600638, 0.00359446, 0.79566205, 0.48911844, 0.44443964])

In [ ]:
np.random.randint(5,50)

35

In [ ]:
np.random.randint(5,50,15)

array([36, 11, 45, 20, 16, 28,  5, 32, 41, 48,  9, 20, 39, 20, 29])

# **Pandas**

In [ ]:
x1=[4,8,4,3,2]

In [ ]:
type(x1)

list

In [ ]:
s1=pd.Series(x1)        #by default index based extraction

In [ ]:
s1

,0
0,4
1,8
2,4
3,3
4,2


In [ ]:
s1=pd.Series(x1,index=['A','B','C','D','E'])

In [ ]:
s1

,0
A,4
B,8
C,4
D,3
E,2


In [ ]:
s1.iloc[2]       #search by index    #index based extraction

np.int64(4)

In [ ]:
s1.loc['C']      #search by labels   #label based extraction

np.int64(4)

In [ ]:
s1.iloc[[1,3]]      #index based extraction for multiple values

,0
B,8
D,3


In [ ]:
s1.loc[['B','D']]     #label based extarction for multiple values

,0
B,8
D,3


In [ ]:
s2=pd.Series([1,2,3,4,5], index=['A','A','B','A','B'])

In [ ]:
s2

,0
A,1
A,2
B,3
A,4
B,5


In [ ]:
s2.iloc[3]

np.int64(4)

In [ ]:
s2.loc['A']

,0
A,1
A,2
A,4


In [ ]:
s3=pd.Series([3,9],index=['F','G'])

In [ ]:
s3

,0
F,3
G,9


In [ ]:
s1=pd.concat([s1,s3])     #concat is working like append

In [ ]:
s1

,0
A,4
B,8
C,4
D,3
E,2
F,3
G,9


In [ ]:
len(s1)

7

In [ ]:
#modify values based on labels
s1.loc['E']=11


In [ ]:
s1

,0
A,4
B,8
C,4
D,3
E,11
F,3
G,9


In [ ]:
#modify values based on index
s1.iloc[4]=10

In [ ]:
s1

,0
A,4
B,8
C,4
D,3
E,10
F,3
G,9


In [ ]:
s2.loc['A']=20

In [ ]:
s2

,0
A,20
A,20
B,3
A,20
B,5


In [ ]:
s1=s1.drop(['E'])

In [ ]:
s1

,0
A,4
B,8
C,4
D,3
F,3
G,9


In [ ]:
s1.drop(s1.index[2])            #it will not delete permanantly

,0
A,4
B,8
D,3
F,3
G,9


In [ ]:
s1

,0
A,4
B,8
C,4
D,3
F,3
G,9


In [ ]:
s1.drop(s1.index[[2,4]])            #if we want to delete multiple values to put values in double square bracket

,0
A,4
B,8
D,3
G,9


In [ ]:
s4=pd.Series([2,3,2,2,4,4,3,4,4,4,4,5,5,2,4,5])

In [ ]:
s4.value_counts()

,count
4,7
2,4
5,3
3,2


In [ ]:
s5=s4.value_counts()

In [ ]:
s5

,count
4,7
2,4
5,3
3,2


In [ ]:
type(s5)

pandas.core.series.Series

In [ ]:
s5.loc[3]

np.int64(2)

In [ ]:
s5.iloc[2]     #for referance  use iloc

np.int64(3)

In [ ]:
np.where(s1==9)  #gives index

(array([5]),)

In [ ]:
s1.index[np.where(s1==9)[0]]    #gives label where value is 9    >>>>>>>>>>>>>>> [0]=first ocuurance

Index(['G'], dtype='object')

In [ ]:
a1=np.array([3,5,4,3,3,3,7,8,9,])

In [ ]:
np.where(a1==3)

(array([0, 3, 4, 5]),)

In [ ]:
len(np.where(a1==3))

1

In [ ]:
len(np.where(a1==3)[0])

4

**Data** **frames**

In [ ]:
mydata=[['A',1234,20000],['B',5678,10000],['C',1357,8000]]

In [ ]:
len(mydata)

3

In [ ]:
mydata=[['A',1234,20000],['B',5678,10000],['C',1357,8000],['D',4567,30000]]

In [ ]:
len(mydata[1])

3

In [ ]:
mydf=pd.DataFrame(mydata)

In [ ]:
mydf

,0,1,2
0,A,1234,20000
1,B,5678,10000
2,C,1357,8000


In [ ]:
temp=pd.DataFrame(mydata,
                  columns=['Name','AccNo','Balance'],
                  index=['nandini','sudhir','khandade','satyabhama']
                  )

In [ ]:
temp

,Name,AccNo,Balance
nandini,A,1234,20000
sudhir,B,5678,10000
khandade,C,1357,8000
satyabhama,D,4567,30000


In [ ]:
mydf

,0,1,2
0,A,1234,20000
1,B,5678,10000
2,C,1357,8000


In [ ]:
mydf.iloc[[1,2]]

,0,1,2
1,B,5678,10000
2,C,1357,8000


In [ ]:
mydf.loc[[1,2]]

,0,1,2
1,B,5678,10000
2,C,1357,8000


In [ ]:
df1=mydf.iloc[[1,2]]

In [ ]:
df1

,0,1,2
1,B,5678,10000
2,C,1357,8000


In [ ]:
df1.iloc[1]

,2
0,C
1,1357
2,8000


In [ ]:
df1.loc[1]      #

,1
0,B
1,5678
2,10000


In [ ]:
df1=mydf.iloc[[1,2]].reset_index(drop=True)     # resets the labels to same as index,

In [ ]:
df1

,0,1,2
0,B,5678,10000
1,C,1357,8000


In [ ]:
#we can only change label .. we can't change index

In [ ]:
df=mydf.iloc[[1,2]].reset_index()

In [ ]:
df

,index,0,1,2
0,1,B,5678,10000
1,2,C,1357,8000


In [ ]:
stu_info={'Name':['A','B','C','D'],'Roll no':[1,2,3,4],'marks':[50,60,75,64]}

In [ ]:
df1=pd.DataFrame(stu_info)

In [ ]:
df1

,Name,Roll no,marks
0,A,1,50
1,B,2,60
2,C,3,75
3,D,4,64


In [ ]:
newdf=pd.DataFrame([['E',7,80],['f',10,65]],columns=df1.columns)

In [ ]:
newdf

,Name,Roll no,marks
0,E,7,80
1,f,10,65


In [ ]:
pd.concat([df1,newdf])

,Name,Roll no,marks
0,A,1,50
1,B,2,60
2,C,3,75
3,D,4,64
0,E,7,80
1,f,10,65


In [ ]:
pd.concat([df1,newdf]).reset_index(drop=True)

,Name,Roll no,marks
0,A,1,50
1,B,2,60
2,C,3,75
3,D,4,64
4,E,7,80
5,f,10,65


In [ ]:
df2=pd.concat([df1,newdf]).reset_index(drop=True)

In [ ]:
df2

,Name,Roll no,marks
0,A,1,50
1,B,2,60
2,C,3,75
3,D,4,64
4,E,7,80
5,f,10,65


In [ ]:
x1=[67,89,75,62,59,82]

In [ ]:
df2['marks2']=x1

In [ ]:
df2

,Name,Roll no,marks,marks2
0,A,1,50,67
1,B,2,60,89
2,C,3,75,75
3,D,4,64,62
4,E,7,80,59
5,f,10,65,82


In [ ]:
df2.at[3,'marks']

np.int64(64)

In [ ]:
df2.at[3,'marks']=74

In [ ]:
df2

,Name,Roll no,marks,marks2
0,A,1,50,67
1,B,2,60,89
2,C,3,75,75
3,D,4,74,62
4,E,7,80,59
5,f,10,65,82


In [ ]:
df2.iat[1,3]

np.int64(89)

In [ ]:
df2.iloc[1,3]

np.int64(89)

In [ ]:
df2.at[3,'marks']

np.int64(74)

In [ ]:
df2.loc[3,'marks']

np.int64(74)

In [ ]:
df2


,Name,Roll no,marks,marks2
0,A,1,50,67
1,B,2,60,89
2,C,3,75,75
3,D,4,74,62
4,E,7,80,59
5,f,10,65,82


In [ ]:
df2.iloc[[0,3,5]]

,Name,Roll no,marks,marks2
0,A,1,50,67
3,D,4,74,62
5,f,10,65,82


In [ ]:
df3=df2.iloc[[0,3,5]].reset_index(drop=True)

In [ ]:
df3

,Name,Roll no,marks,marks2
0,A,1,50,67
1,D,4,74,62
2,f,10,65,82


In [ ]:
df2

,Name,Roll no,marks,marks2
0,A,1,50,67
1,B,2,60,89
2,C,3,75,75
3,D,4,74,62
4,E,7,80,59
5,f,10,65,82


In [ ]:
mySubject=df2[['Name','marks2']]

In [ ]:
mySubject

,Name,marks2
0,A,67
1,B,89
2,C,75
3,D,62
4,E,59
5,f,82


In [ ]:
df2.iloc[:,[1,2]]

,Roll no,marks
0,1,50
1,2,60
2,3,75
3,4,74
4,7,80
5,10,65


In [ ]:
df2['marks2']

,marks2
0,67
1,89
2,75
3,62
4,59
5,82


In [ ]:
df2.marks2

,marks2
0,67
1,89
2,75
3,62
4,59
5,82


In [ ]:
df2.drop([1,4],axis=0)

,Name,Roll no,marks,marks2
0,A,1,50,67
2,C,3,75,75
3,D,4,74,62
5,f,10,65,82


In [ ]:
df2.drop(['Roll no','marks'],axis=1)

,Name,marks2
0,A,67
1,B,89
2,C,75
3,D,62
4,E,59
5,f,82
